# Generated by Django 4.1.1 on 2022-09-12 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=150)),
                ('comment_email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('comment_published', models.BooleanField()),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
